In [1]:
import pandas as pd
import numpy as np


In [2]:
df1=pd.read_csv('x_train.csv')

In [3]:
df2=pd.read_csv('y_train.csv')

In [4]:
df1.head()

x
0 -0.289307
1 -0.588810
2  1.027507
3 -0.259013
4  0.782043

In [5]:
df2.head()

y
0  -0.091101
1 -53.467721
2  75.457009
3 -12.025286
4  57.414187

In [6]:
X_train=df1
y_train=df2

In [7]:
from sklearn.linear_model import LinearRegression as lr
lr_model=lr()
lr_model.fit(X_train,y_train)

LinearRegression()

In [8]:
lr_model.coef_,lr_model.intercept_

(array([[80.54363185]]), array([3.72798828]))

In [9]:
df3=pd.read_csv('X_test.csv')

In [10]:
df3.head()

x
0 -1.877944
1 -0.869032
2 -2.530182
3  2.760205
4  0.591000

In [11]:
X_test=df3

In [12]:
print(X_test)

             x
0    -1.877944
1    -0.869032
2    -2.530182
3     2.760205
4     0.591000
...        ...
1245 -0.168058
1246  0.932223
1247  0.128008
1248 -0.278038
1249 -0.680425

[1250 rows x 1 columns]


In [13]:
y_pred = lr_model.predict(X_test) 

In [14]:
print(y_pred)

[[-147.52847525]
 [ -66.26699842]
 [-200.06209345]
 ...
 [  14.0382031 ]
 [ -18.66616899]
 [ -51.07594693]]


In [15]:
arr=np.array([10])
hours=arr.reshape(-1,1)
req_pred=lr_model.predict(hours)

In [16]:
req_pred

array([[809.16430683]])